"""
based on brand , gender and category the sector wise comparisons change hence the sectors
"""

sector_brunch = {
    'Levis': {
        'Male': {
            'Tops': [
                'Capsule',
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Destruction',
                'Field PDS Name',
                'Garment Developr Name',
                'Graphic Type',
                'Local Development For',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Product Dev.Center Value',
                'Product Line',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Stretch Type',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Wovens Pattern Type',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center',
                'Special Tab Color',
                'Performance'

            ],
            'Bottoms': [
                'Capsule',
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Destruction',
                'Field PDS Name',
                'Garment Developr Name',
                'Hem Type',
                'Local Development For',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Non-Denim Color',
                'Product Dev.Center Value',
                'Product Line',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Stretch Type',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center',
                'Special Tab Color',
                'Performance'
            ]
        }, 
        'Female' : {
            'Tops': [
                'Capsule',
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Destruction',
                'Field PDS Name',
                'Garment Developr Name',
                'Graphic Type',
                'Local Development For',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Product Dev.Center Value',
                'Product Line',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Stretch Type',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Wovens Pattern Type',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center',
                'Special Tab Color',
                'Performance'

            ],
            'Bottoms': [
                'Capsule',
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Destruction',
                'Field PDS Name',
                'Garment Developr Name',
                'Hem Type',
                'Local Development For',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Non-Denim Color',
                'Product Dev.Center Value',
                'Product Line',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Program',
                'Rigid Indicator',
                'Season First Introduced',
                'Stretch Type',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center',
                'Special Tab Color',
                'Performance'
            ]
        }
    },
    'Dockers': {
        'Male': {
            'Tops': [
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Field PDS Name',
                'Garment Developr Name',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Non-Denim Color',
                'PC9 Certified Water<Less Finish?',
                'Product Dev.Center Value',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Wovens Pattern Type',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center',
                'Performance',
            ],
            'Bottoms' : [
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Field PDS Name',
                'Garment Developr Name',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'PC9 Certified Water<Less Finish?',
                'Product Dev.Center Value',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center',
                'Performance'

            ]
        },
        'Female': {
            'Tops': [
                'Capsule',
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Field PDS Name',
                'Garment Developr Name',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Non-Denim Color',
                'PC9 Certified Water<Less Finish?',
                'Product Dev.Center Value',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Wovens Pattern Type',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center',
                'Performance'

            ], 
            'Bottoms' : [
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Field PDS Name',
                'Garment Developr Name',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'PC9 Certified Water<Less Finish?',
                'Product Dev.Center Value',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center',
                'Performance'

            ]
        }
    },
    'Denizen': {
        'Male' : {
            'Tops' : [
                'Capsule',
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Field PDS Name',
                'Garment Developr Name',
                'Hem Type',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center',

            ],
            'Bottoms' : [
                'Capsule',
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Field PDS Name',
                'Garment Developr Name',
                'Hem Type',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Product Dev.Center Value',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center'

            ]
        }, 
        'Female' : {
            'Tops' : [
                'Capsule',
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Field PDS Name',
                'Garment Developr Name',
                'Hem Type',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Product Dev.Center Value',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center'

            ],
            'Bottoms' : [
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Field PDS Name',
                'Garment Developr Name',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'PC9 Certified Water<Less Finish?',
                'Product Dev.Center Value',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center',
                'Performance'
            ]
        }
    }, 
    'Signature': {
        'Male': {
            'Tops': [
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Field PDS Name',
                'Garment Developr Name',
                'Hem Type',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Product Dev.Center Value',
                'Product Line',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center',

            ],
            'Bottoms' : [
            'Colorway Code',
            'Colorway Name',
            'Construction Line',
            'Designer Name',
            'Destroy Sample Ind',
            'Field PDS Name',
            'Garment Developr Name',
            'Hem Type',
            'Local Production',
            'Material Type Value',
            'Merch Fabric Type',
            'Product Dev.Center Value',
            'Product Line',
            'Product Manager Name',
            'Product Marketing Name',
            'Product Status',
            'Product Type',
            'Rigid Indicator',
            'Season First Introduced',
            'Target COGS',
            'Target FOB',
            'Target Volume',
            'Product Segmentation',
            'Product Segmentation',
            'Profit Center',
            'Profit Center',
            'Profit Center'

            ],
        },
        'Female': {
            'Tops': [
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Field PDS Name',
                'Garment Developr Name',
                'Hem Type',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Product Dev.Center Value',
                'Product Line',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center'

            ],
            'Bottoms' : [
                'Colorway Code',
                'Colorway Name',
                'Construction Line',
                'Designer Name',
                'Destroy Sample Ind',
                'Field PDS Name',
                'Garment Developr Name',
                'Hem Type',
                'Local Production',
                'Material Type Value',
                'Merch Fabric Type',
                'Product Dev.Center Value',
                'Product Line',
                'Product Manager Name',
                'Product Marketing Name',
                'Product Status',
                'Product Type',
                'Rigid Indicator',
                'Season First Introduced',
                'Target COGS',
                'Target FOB',
                'Target Volume',
                'Product Segmentation',
                'Product Segmentation',
                'Profit Center',
                'Profit Center',
                'Profit Center'

            ]
        }
    }
}




def sectorSelect(brand = '', gender = '' , category = '') -> list[str] :
    '''
    based on the selection the entity sector list is returned
    '''
    return sector_brunch[brand][gender][category]


# if __name__ == '__main__':
#     sectorSelect()